Repository ovh-ux/ng-ovh-api-wrappers, pull requests merged in 2019-07, with the labels that each got.

#15 feat(iceberg): return response headers
  src/iceberg/request-upgrader.service.js
Labels: enhancement

#16 Release v4.0.0
  src/iceberg/request-upgrader.service.js
Labels: release :package:

#21 fix(iceberg): parse response data
  src/iceberg/request-upgrader.service.js
Labels: bug

#27 build(dev-deps): upgrade some dev dependencies
  package.json
  yarn.lock
Labels: dependencies

#28 build: update lint-staged configuration
  .lintstagedrc.json
Labels: build

#26 Release v4.0.2
  .eslintrc.json
  .lintstagedrc.json
  README.md
  package.json
  yarn.lock
Labels: release :package:

#32 docs: generate changelog.md file …
  CHANGELOG.md
Labels: documentation :memo:
